apps/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'accounts'

urlpatterns = [
    # Autenticação
    path("login/", views.UserLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("register/", views.register, name="register"),

    # Perfil (Esta é a rota da task atual)
    path("me/", views.profile, name="profile"),
    
    # Configurações
    path("me/edit/", views.profileEdit, name="profile_edit"),
    path("me/artisan/", views.becomeArtisian, name="settings_artisian"),

    # Placeholders futuros
    path('me/orders/', views.usersOrders, name='orders'),
    path('me/favorites/', views.favoriteProduct, name='favorites'),
    
    # Endereços
    path('me/addresses/', views.addressesList, name='addresses'),
    path('me/addresses/register', views.AddressesRegister.as_view(), name='addresses_register'),
    path("me/addresses/<int:address_id>/edit/", views.addressEdit, name="settings_address"),

    path("me/addresses/<int:address_id>/delete/", views.addressDelete, name="delete_address"),
    # NOVA ROTA: Definir padrão
    path("me/addresses/<int:address_id>/default/", views.addressSetDefault, name="set_default_address"),
]

apps/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    # path("list/", views.list, name="list"),
    path("add/", views.addToCart, name="add"),
    path("cart/", views.viewCart, name="cart"),
    path("shipping/", views.shipping, name="shipping"),
    path("payment/", views.payment, name="payment"),
    path("checkout/", views.checkout, name="checkout"),
    path("approved/<str:transaction_id>", views.approved, name="approved"),
 
    path('<int:order_id>/', views.orders_detail, name='detail'),

    # Carrinho
    path('<int:item_id>/remove/', views.removeCartItem, name='remove_item'),
    path('<int:item_id>/update/<str:action>/', views.updateCartItem, name='update_item')

]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

from apps.core.views import (
    error_404_view,
    error_500_view,
    error_403_view,
    error_400_view
)

handler404 = error_404_view
handler500 = error_500_view
handler403 = error_403_view
handler400 = error_400_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("apps.accounts.urls")),
    path("stores/", include("apps.stores.urls")),
    path("products/", include("apps.products.urls")),
    path("orders/", include("apps.orders.urls")),
    path("chats/", include("apps.chats.urls")),
    path("reviews/", include("apps.reviews.urls")),
    path("", include("apps.core.urls")),
    path("", include("apps.utils.urls")),


    # Teste com o debug = true para visualizar as páginas de erro
    path("teste-400/", TemplateView.as_view(template_name="errors/400.html")),
    path("teste-403/", TemplateView.as_view(template_name="errors/403.html")),
    path("teste-404/", TemplateView.as_view(template_name="errors/404.html")),
    path("teste-500/", TemplateView.as_view(template_name="errors/500.html")),
]


if settings.DEBUG:
    # Adiciona a rota para servir arquivos de mídia (MEDIA_URL) usando o caminho
    # definido em MEDIA_ROOT (no seu caso, BASE_DIR / 'media')
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    # (servir arquivos estáticos no desenvolvimento local)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from apps.accounts.models import Address
from .models import Order, ProductVariant, Cart, CartItem, OrderProduct
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.db import transaction
from django.db.models import F, Sum
from django.core.exceptions import ValidationError
import uuid


@require_POST 
def addToCart(request):
    if request.method == 'POST':
        variant_id = request.POST.get('variant_id')
        quantity = int(request.POST.get('quantity'))
        
        variant = get_object_or_404(ProductVariant, pk=variant_id)
        cart_obj, _ = Cart.objects.new_or_get(request)

        cart_item = CartItem.objects.filter(cart=cart_obj, product_variant=variant).first()
        quantity_in_cart = cart_item.quantity if cart_item else 0

        if variant.type == 'STOCK':
            total_desired = quantity_in_cart + quantity
            
            if total_desired > variant.stock:
                remaining = variant.stock - quantity_in_cart
                
                if remaining > 0:
                    messages.error(request, f'Estoque insuficiente. Você já tem {quantity_in_cart} no carrinho e só restam mais {remaining} unidades.')
                else:
                    messages.error(request, 'Você já adicionou todo o estoque disponível deste produto ao seu carrinho.')
                
                return redirect(request.META.get('HTTP_REFERER', '/'))

        if cart_item:
            cart_item.quantity += quantity
            cart_item.save()
        else:
            CartItem.objects.create(
                cart=cart_obj, 
                product_variant=variant, 
                quantity=quantity
            )

        messages.success(request, f'Produto adicionado ao carrinho!')
        return redirect(request.META.get('HTTP_REFERER', '/'))
        
    return redirect('/')

def viewCart(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)

    items = cart_obj.items.select_related('product_variant').all()

    context = {'cart': cart_obj, 'items': items}
    
    return render(request, 'orders/shopping_cart.html', context)

def updateCartItem(request, item_id, action):
    if request.method == 'POST':        
        item = get_object_or_404(CartItem, pk=item_id)

        cart_obj, _ = Cart.objects.new_or_get(request)

        if item.cart == cart_obj:
            if not item.product_variant.is_active:
                messages.error(request, 'Este produto não está mais disponível para venda.')
                return redirect(request.META.get('HTTP_REFERER', '/'))
            
            if action == 'increase':
                quantity_desired = item.quantity + 1
                if item.product_variant.type == 'STOCK' and quantity_desired > item.product_variant.stock:
                    messages.warning(request, 'O estoque máximo já foi adicionado ao seu carrinho.')
                else:
                    item.quantity += 1
                    item.save()

            elif action == 'decrease':
                new_quantity = item.quantity - 1

                if new_quantity <= 0:
                    item.delete()
                    messages.warning(request, 'Item removido do carrinho')
                else:
                    item.quantity -= 1
                    item.save()
            else:
                messages.error(request, 'Você não pode realizar esta ação.')

        else:
            messages.error(request, 'Você não tem permissão para alterar este item.')

        return redirect(request.META.get('HTTP_REFERER', '/'))

    return redirect('/')

def removeCartItem(request, item_id):
    if request.method == 'POST':        
        item = get_object_or_404(CartItem, pk=item_id)

        cart_obj, _ = Cart.objects.new_or_get(request)

        if item.cart == cart_obj:
            item.delete()
            messages.warning(request, 'Item removido do carrinho')
        else:
            messages.error(request, 'Você não tem permissão para remover este item.')

        return redirect(request.META.get('HTTP_REFERER', '/'))
    
    return redirect('/')

@login_required
def shipping(request):
    cart_obj, _ = Cart.objects.new_or_get(request)

    if not cart_obj.items.exists():
        messages.warning(request, "O carrinho está vazio!")
        return redirect('orders:cart')        
    else:
        addresses = Address.objects.filter(user=request.user)

        for item in cart_obj.items.all():
            product = item.product_variant
            if not product.is_active:
                messages.warning(request, f'O produto {product.description} não está disponivel para venda. Remova-o do carrinho e prossiga com a compra')
                return redirect('orders:cart')
                
            if product.type == 'STOCK':
                if product.stock < item.quantity:
                    messages.warning(request, f'O produto {product.description} esgotou o estoque. Remova-o do carrinho e prossiga com a compra.')
                    return redirect('orders:cart')

    context = {'addresses': addresses, 'cart_obj': cart_obj}

    return render(request, 'orders/shipping.html', context)

@login_required
def payment(request):
    if request.method == 'POST':
        address_id = request.POST.get('shipping_address')

        shipping_method = request.POST.get('shipping')

        if not address_id:
            messages.warning(request, "Informe um endereço para prosseguir.")
            return redirect(request.META.get('HTTP_REFERER', '/'))
        
        if not shipping_method:
            messages.warning(request, "Selecione o frete para prosseguir.")
            return redirect(request.META.get('HTTP_REFERER', '/'))

        cart_obj, _ = Cart.objects.new_or_get(request)

    context = {'address_id':address_id, 'cart': cart_obj}

    return render(request, 'orders/payment.html', context)

@login_required
def checkout(request):
    if request.method == 'POST':
        address_id = request.POST.get('shipping_address')
        
        try:
            address = Address.objects.get(pk=address_id, user=request.user)
        except Address.DoesNotExist:
            messages.error(request, "Endereço selecionado é inválido.")
            return redirect('orders:shipping')

        cart_obj, _ = Cart.objects.new_or_get(request)
        cart_items = cart_obj.items.select_related('product_variant', 'product_variant__product__store').all()

        if not cart_items.exists():
            messages.warning(request, "Seu carrinho está vazio.")
            return redirect('orders:cart')

        # Cria um dicionário: { <Store A>: [Item1, Item2], <Store B>: [Item3] }
        items_by_store = {}
        for item in cart_items:
            store = item.product_variant.product.store
            if store not in items_by_store:
                items_by_store[store] = []
            items_by_store[store].append(item)

        try:
            with transaction.atomic():
                
                current_transaction_id = str(uuid.uuid4())

                for store, items_list in items_by_store.items():
                    store_total = sum(item.subtotal for item in items_list)

                    order = Order.objects.create(
                        store=store,
                        user=request.user,
                        status='PENDING',
                        total_amount=store_total,
                        shipping_street=address.street,
                        shipping_number=address.number,
                        shipping_neigh=address.neighborhood, 
                        shipping_city=address.city,
                        shipping_state=address.state,
                        shipping_cep=address.cep,
                        shipping_complement=address.complement,
                        transaction_id=current_transaction_id
                    )

                    for item in items_list:
                        product = item.product_variant

                        if not product.is_active:
                            raise ValidationError(f"O produto {product.description} não está mais disponível.")

                        if product.type == 'STOCK' and product.stock < item.quantity:
                            raise ValidationError(f"Estoque insuficiente para {product.description}.")

                        if product.type == 'STOCK':
                            product.stock = F('stock') - item.quantity
                            product.save()

                        OrderProduct.objects.create(
                            order=order,
                            product_variant=product,
                            quantity=item.quantity,
                            price_at_purchase=product.price 
                        )

                cart_obj.items.all().delete() 

                request.session['last_approved_transaction'] = current_transaction_id

            return redirect('orders:approved', transaction_id=current_transaction_id) 

        except ValidationError as e:
            messages.warning(request, e.message)
            return redirect('orders:cart')
            
        except Exception as e:
            messages.error(request, "Ocorreu um erro ao processar seu pedido. Nada foi cobrado.")
            return redirect('orders:cart')

    return redirect('orders:cart')

@login_required()
def approved(request, transaction_id):
    allowed_id = request.session.get('last_approved_transaction')

    if not allowed_id or allowed_id != transaction_id:
        return redirect('accounts:orders')
    
    orders = Order.objects.filter(user=request.user, transaction_id=transaction_id).select_related('store').prefetch_related('items')

    if not orders.exists():

apps/orders/templates/orders/payment.html
{% extends "shared/base.html" %}
{% load static %}

{% block title %}Método de Pagamento{% endblock %}


{% block style %}
<link rel="stylesheet" href="{% static 'orders/css/shared/payment.css' %}">
<link rel="stylesheet" href="{% static 'orders/css/shared/shopping_cart.css' %}">
<link rel="stylesheet" href="{% static 'orders/css/shared/shipping.css' %}">
{% endblock style %}

{% block main %}
<div class="container my-5">
    <form action="{% url 'orders:checkout' %}" method="POST">
        {% csrf_token %}
        <div class="row g-4">
            <div class="col-lg-8">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h2 id="my-cart">Métodos de Pagamento</h2>
                </div>
                <div class="delivery-section" >   
                    <h2 class="section-title">Selecione a forma</h2>

                    {% include 'orders/partials/_forms_select.html' with selected=True data_method="credit" select=True form_pay="Cartão de Crédito" description_pay="Visa, Mastercard, Elo e mais" %}

                    {% include 'orders/partials/_forms_select.html' with data_method="pix" selected=False form_pay="Pix" description_pay="Aprovação instantânea" %}

                    {% include 'orders/partials/_forms_select.html' with data_method="boleto" selected=False form_pay="Boleto Bancário" description_pay="Vencimento em 3 dias úteis" %}

                    <div class="mt-4 credit_card_form">
                        <div class="mb-3">
                            <label for="cardNumber" class="form-label">Número do Cartão</label>
                            <input type="text" class="form-control" id="cardNumber" value="1234 5678 9012 3456" placeholder="0000 0000 0000 0000">
                        </div>
                        
                        <div class="mb-3">
                            <label for="cardName" class="form-label">Nome no Cartão</label>
                            <input type="text" class="form-control" id="cardName" value="MARIA SILVA SANTOS" placeholder="Como aparece no cartão">
                        </div>
                        
                        <div class="row">
                            <div class="col-md-4 mb-3">
                                <label for="expiry" class="form-label">Validade</label>
                                <input type="text" class="form-control" id="expiry" value="12/25" placeholder="MM/AA">
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="cvv" class="form-label">CVV</label>
                                <select class="form-select cvv-select" id="cvv">
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                </select>
                            </div>
                        </div>
                            
                        <div class="alert bg-security d-flex align-items-center" role="alert">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shield-check me-2" viewBox="0 0 16 16">
                                <path d="M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.897.533.12.057.218.095.302.11l.022.005.017.002.012.001H12a.5.5 0 0 0 .5-.5V6.461c0-.135-.024-.254-.08-.359a.6.6 0 0 0-.22-.238.56.56 0 0 0-.326-.084H8a.5.5 0 0 1 0-1h3.5A1.5 1.5 0 0 1 13 5.5V8a.5.5 0 0 1-.5.5H12a.5.5 0 0 0-.47.331c-.145.326-.38.539-.66.65a1.4 1.4 0 0 1-.555.13 1.37.37 0 0 1-.82-.12 3.2 3.2 0 0 1-1.055-.64.6.6 0 0 1-.167-.323c-.033-.11-.042-.22-.01-.328a.3.3 0 0 0-.014-.135L10.1 2.45a.4.4 0 0 0-.454-.38 1.1 1.1 0 0 1-.165-.04 1.1 1.1 0 0 1-.204-.06.6.6 0 0 0-.236-.051.5.5 0 0 0-.5.5v.87a1.4 1.4 0 0 1-1.53 1.38l-1.88-.643a.5.5 0 0 0-.45.035.3.3 0 0 0-.131.17l-.166.83a.5.5 0 0 1-.57.408L2.58 9.78a.3.3 0 0 0-.13.012.5.5 0 0 0-.25.189v.75a.5.5 0 0 0 .5.5h3.5a.5.5 0 0 1 .497.54l-.127 1.849a.5.5 0 0 1-.5.45h-1.87a.5.5 0 0 0-.492.408L.002 13.331a.5.5 0 0 0 .497.568h15.005a.5.5 0 0 0 .497-.568L13.502 2.33a.5.5 0 0 0-.497-.408h-1.87a.5.5 0 0 1-.5-.45l-.127-1.848a.5.5 0 0 0-.57-.408L8.924 1.569a.5.5 0 0 1-.164-.053.5.5 0 0 0-.338-.049.5.5 0 0 0-.23.123L6.24 3.3a.5.5 0 0 0-.09.406.6.6 0 0 1-.035.086m.522 2.707 1.065-.638a.5.5 0 0 1 .537.05l1.855 1.482a.5.5 0 0 1 .114.632l-.439.937a.5.5 0 0 1-.716.219L7.28 5.902a.5.5 0 0 1 .253.545l.535 2.139a.5.5 0 0 1-.575.603l-2.357-.471a.5.5 0 0 1-.191-.079l-1.02-.816a.5.5 0 0 1-.055-.777l.517-1.243a.5.5 0 0 1 .598-.281z"/>
                            </svg>
                            <span>Suas informações estão protegidas com criptografia SSL de 256 bits</span>
                        </div>
                    </div>
                </div>
            </div> 
            <div class="col-lg-4">
                <div class="summary-card">
                    <h3>Resumo do Pedido</h3>

                    <div class="summary-line">
                        <span>Subtotal</span>
                        <span>R$ {{ cart.total|floatformat:2 }}</span>
                    </div>

                    <div class="summary-line">
                        <span>Frete</span>
                        <span>Grátis</span>
                    </div>

                    <hr class="summary-divider">

                    <div class="summary-line total">
                        <strong>Total</strong>
                        <strong class="total-price">R$ {{ cart.total|floatformat:2 }}</strong>
                    </div>    <input type="hidden" name="shipping_address" value="{{ address_id }}">

                    <input type="hidden" name="shipping_address" value="{{ address_id }}">

                    <button type="submit" class="btn btn-green">Finalizar compra</button>
                </div>        
            </div>
        </div>
    </form>
</div>


<script src="{% static 'orders/js/payment.js' %}"></script>

{% endblock %}

apps/orders/templates/orders/shipping.html
{% extends "shared/base.html" %}
{% load static %}
{% block title %}Confirmar Endereço{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'orders/css/shared/shopping_cart.css' %}">
<link rel="stylesheet" href="{% static 'orders/css/shared/shipping.css' %}">
{% endblock style %}

{% block main %}
<div class="container my-5">
  <form action="{% url 'orders:payment' %}" method="POST">
    {% csrf_token %}
    <div class="row g-4">
      <!-- Coluna Esquerda: Opções de Entrega -->
      <div class="col-lg-8">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h2>Opções de Entrega</h2>
        </div>
    
        <!-- Seção de Endereços -->
        <div class="delivery-section">
          <h2 class="section-title">Selecione o Endereço</h2>
          
          {% if addresses %}
            {% for address in addresses %}
              <div class="address-card">
                <div class="address-icon">
                  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#D26B21" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                    <polyline points="9 22 9 12 15 12 15 22"></polyline>
                  </svg>
                </div>
                <div class="address-content">
                  <div class="address-header">
                    <span class="address-type">{{ address.complement }}</span>
                    {% comment %} <a href="#" class="address-edit">Editar</a> {% endcomment %}
                  </div>
                  <div class="address-details">
                    <p>{{ address.street }}, {{ address.number }}</p>
                    <p>Bairro {{ address.neighborhood }}</p>
                    <p>{{ address.city }}, {{ address.state }} - {{ address.cep }} </p>
                  </div>
                </div>
                <div class="d-flex align-items-center">
                  <input type="radio" name="shipping_address" value="{{ address.address_id }}" id="address_{{ address.pk }}" {% if forloop.first %}checked{% endif %}>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <p class="space">Você ainda não possui endereço cadastrado</p>
          {% endif %}
            <a href="{% url 'accounts:addresses_register' %}?next={% url 'orders:shipping' %}" class="btn btn-secondary">
              Adicionar Novo Endereço
            </a>
        </div>
        
        <!-- Seção de Frete -->
        <div class="delivery-section mt-4">
          <h2 class="section-title">Selecione o Frete</h2>
          
          <!-- Opção 1 -->
          <div class="shipping-option">
            <div class="d-flex align-items-center">
              <input type="radio" name="shipping" value="standard">
            </div>
            <div class="shipping-content">
              <div class="shipping-header">
                <span class="shipping-name">Entrega Padrão</span>
                <span class="shipping-price">Grátis</span>
              </div>
              <p class="shipping-description">Receba em 5-7 dias úteis</p>
            </div>
          </div>
          
          <!-- Opção 2 -->
          <div class="shipping-option">
            <div class="d-flex align-items-center">
              <input type="radio" name="shipping" value="pickup">
            </div>
            <div class="shipping-content">
              <div class="shipping-header">
                <span class="shipping-name">Retirada na Loja</span>
              </div>
              <p class="shipping-description">Busque seu pedido em nossa loja física</p>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Coluna Direita: Resumo do Pedido -->
      <div class="col-lg-4">
        <div class="summary-card">
          <h3>Resumo do Pedido</h3>

          <div class="summary-line">
              <span>Subtotal</span>
              <span>R$ {{ cart_obj.total|floatformat:2 }}</span>
          </div>

          {% if cart_obj %}
              <div class="summary-line">
                  <span>Frete</span>
                  <span>R$ 0,00</span>
              </div>
          {% endif %}

          <hr class="summary-divider">

          <div class="summary-line total">
              <strong>Total</strong>
              <strong class="total-price">R$ {{ cart_obj.total|floatformat:2 }}</strong>
          </div>


          <button type="submit" class="btn btn-green">Continuar</button>
          <a href="{% url 'index' %}" class="btn btn-primary w-100 py-3">
              Adicionar produtos
          </a>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock main %}

{% block script %}
<script src="{% static 'orders/js/shipping.js' %}"></script>
{% endblock script %}

apps/orders/templates/orders/shopping_cart.html
{% extends 'shared/base.html' %}
{% load static %}
 
{% block title %}Carrinho{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{% static 'orders/css/shared/shopping_cart.css' %}" >
{% endblock %}
 
{% block main %}
  <div class="container my-5">
    <div class="row g-4">
      
      <div id="my-cart-primary" class="col-lg-8">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h2 id="my-cart">Meu Carrinho</h2>

          {% if cart.total_items == 1 %}
            <span id="qtnd-itens" class="text-muted">{{ cart.total_items }} item</span>
          {% endif %}

          {% if cart.total_items > 1 %}
            <span id="qtnd-itens" class="text-muted">{{ cart.total_items }} itens</span>
          {% endif %}
        
        </div>

        {% if items %}
          {% for item in items %}
            <div class="cart-item-card">
              {% with item.product_variant.images.first as v_img %}
                  {% if v_img %}
                      <img src="{{ v_img.image.url }}" alt="{{ item.product_variant.product.name }}" class="cart-item-image" />
                  {% else %}
                      <img src="/static/img/no-image.png" class="cart-item-image" />
                  {% endif %}
              {% endwith %}

              <div class="cart-item-info">
                <h4>{{ item.product_variant.product.name }}</h4>
                <p class="description_product">Descrição: {{ item.product_variant.description }}</p>
                <p>Vendido por: {{ item.product_variant.product.store.name }}</p> 
                
                {% if item.product_variant.is_active %}
                  <div class="cart-item-price">
                    <strong>R$ {{ item.price|floatformat:2 }}</strong>
                  </div>
                {% else %}
                  <div class="cart-item-price">
                    <strong class="line">R$ {{ item.price|floatformat:2 }}</strong>
                  </div>
                {% endif %}
              </div>

              <div class="cart-item-actions">
                <form action="{% url 'orders:remove_item' item.pk %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="remove">Remover</button>
                </form>

                {% if item.product_variant.is_active %}
                  <div class="quantity-selector">
                    <form action="{% url 'orders:update_item' item.pk 'decrease' %}" method="POST" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn-qty">-</button>
                    </form>

                    <span class="quantity-value">{{ item.quantity }}</span>

                    <form action="{% url 'orders:update_item' item.pk 'increase' %}" method="POST" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn-qty">+</button>
                    </form>
                  </div>
                {% else %}
                  <span class="text-danger">Produto Indisponível</span>
                {% endif %}
              </div>
            </div>
          {% endfor %}

        {% else %}
          <h4>Não há produtos no carrinho</h4>
        {% endif %}

      </div> 

      <div class="col-lg-4">
        <div class="summary-card">
          <h3>Resumo do Pedido</h3>

          <div class="summary-line">
              <span>Subtotal</span>
              <span>R$ {{ cart.total|floatformat:2 }}</span>
          </div>

          {% if items %}
              <div class="summary-line">
                  <span>Frete</span>
                  <span>Grátis</span>
              </div>
          {% endif %}

          <hr class="summary-divider">

          <div class="summary-line total">
              <strong>Total</strong>
              <strong class="total-price">R$ {{ cart.total|floatformat:2 }}</strong>
          </div>

          {% if items %}
            <a href="{% url 'orders:shipping' %}" class="btn btn-green">
              Continuar
            </a>
          {% endif %}
          <a href="{% url 'index' %}" class="btn btn-primary w-100 py-3">
              Adicionar produtos
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'orders/js/shopping_cart.js' %}"></script>
{% endblock scripts %}